name = "M.P.D-SW"
fullname = "Multipurpose Download Software"
description = f"{fullname} is a tool to download different stuff from the Internet such as GitHub, YouTube, Minecraft and more!"
CopyrightText = "M.P.D-SW © 2023"
__version__ = version = "1.1"